### ISSUE TITLE
Plugin blocks image resizing

### ISSUE THREAD

**Issue by caglarongan** [johansan/obsidian-featured-image#5] opened 2024-12-10 03:41 UTC
When I try to resize a featured image like `![[sample.png|450]]` , plugin interferes and doesn't allow this change.

When I resize an image via plugins like *Mousewheel Image Zoom* or *Image Converter*, featured image property value changes as if I'm adding `|number` to it. But it corrects itself immediately.

Is this a bug or a feature?

**Comment by johansan** [comment] 2024-12-11 18:27
Hi, any chance you could do a screen capture and post it to show me? Would help me debug it!

**Comment by technotherion** [comment] 2024-12-12 14:22
I am using both *Mousewheel Image Zoom* and *Image Converter* in the same vault as *Featured Image* and am not able to reproduce said issues. 

With *Mousewheel Image Zoom*, I am able to hit the alt key and scroll up and down to change the image preview size. Upon leaving and returning to the same note, the changes stay. I am not having the size revert. 

![fJ97Beh](https://github.com/user-attachments/assets/971eb748-e3a1-45f2-bf6d-40217dcf9a91)

When I use Image Converter,  it is changing the size of the image itself and not the preview. E.g I made this image 100px by 100px, but it is displaying at 350px. 

![image](https://github.com/user-attachments/assets/9462792e-77e8-4090-8757-f98459d23a52)

What other plugins are you using, @caglarongan? I would look for anything like Contextual Typography (no longer required for Minimal Theme) or any other plugins that affect image display css.

**Comment by caglarongan** [comment] 2024-12-12 18:10
@technotherion I think you can't reproduce because you're not resizing the featured image. As I can see there's another image before the one you modify.
Here's a demonstration on a sandbox vault.
I'm using Obsidian 1.7.7 

https://github.com/user-attachments/assets/f316bde6-32ff-4867-9d60-2bc1c517ca20

**Comment by johansan** [comment] 2024-12-12 18:44
Hi, thanks, I see the issue now and can reproduce it. 

It happens because both "Image Converter" and "Mousewheel Image zoom" just tries to find the first occurance of the image that is being scaled, and they do not skip the frontmatter section when checking for the image name. They also do not verify that the image name is embedded within markdown or wiki links.

You can easily verify their bad behaviour this way:

1. Disable the plugin "Featured Image"
2. Add an image called ![[2.jpg]] or whatever file name to your document
3. Try an resize it with Image Converter and Mousewheel Image zoom. It should work great.
4. Then add a text line above your image, so your document looks like:

**Writing 2.jpg here will break Image Converter and Mousewheel Image zoom.

![[2.jpg]]**

Use the same filename in both places. This will completely break both plugins.

Unfortunately this is a bug in both of the other plugins. They should not touch the frontmatter, and they should both ignore the file name if it's not a wiki or md link.

Not sure if this is fixable on my part, I will think about it.

**Comment by johansan** [comment] 2024-12-12 19:01
If I cannot come up with a solution on my side, I guess the best way forward is to use a template for the folders you want to use Featured Image, and then activate the settings to only update feature if property already exists, and do not remove property if feature is empty.

**Comment by caglarongan** [comment] 2024-12-12 19:40
Oh I see !
I should open an issue on their repo and link to this convo, it's better to be fixed on that end imho.

Btw, did you see my latest comment on the other closed issue? I don't know if github creates a notification for closed issues?

**Comment by johansan** [comment] 2024-12-13 10:09
Thanks, I didn't see it - thanks for letting me know! I just posted a clarification in that thread, would be super to get this fixed in both Image Converter and Mousewheel Image zoom!

**Comment by caglarongan** [comment] 2024-12-13 21:00
It was a nice *community* moment :)
I meant the comment here though: https://github.com/johansan/obsidian-featured-image/issues/4#issuecomment-2539618878

**Comment by johansan** [comment] 2024-12-16 08:58
Thanks, I have fixed that other issue, and also added a "Known Issues" to the README. The authors on **Mousewheel Image Zoom** does not seem so active, but let's hope they fix their issue too like the **Image Resizer** team.

**Closed** 2024-12-18 08:42 UTC
